### ISSUE TITLE
Crash when opening Creative Tabs Spells page.

### ISSUE THREAD

**Issue by AzureDoom** [Meldexun/ExtraSpells#10] opened 2019-12-18 22:18 UTC
Version of Extra Spells: 1.0.3
Version of EB Wizardry: 2.4.6

Crash log:
https://gist.github.com/AzureZhen/a39a1b3575051754697f59f691a4b143

**Comment by Meldexun** [comment] 2019-12-18 23:10
Duplicate of #9

**Closed as completed by Meldexun** 2019-12-18 23:10 UTC
